//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationSystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class EndarProcessorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EndarProcessorSettings defaultInstance = ((EndarProcessorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EndarProcessorSettings())));
        
        public static EndarProcessorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int TimeSpan {
            get {
                return ((int)(this["TimeSpan"]));
            }
            set {
                this["TimeSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EnDAR@tetratech.com")]
        public string EmailFrom {
            get {
                return ((string)(this["EmailFrom"]));
            }
            set {
                this["EmailFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseInstallPathForLogging {
            get {
                return ((bool)(this["UseInstallPathForLogging"]));
            }
            set {
                this["UseInstallPathForLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kateryna.sayenko@tetratech.com")]
        public string DefaultRecipient {
            get {
                return ((string)(this["DefaultRecipient"]));
            }
            set {
                this["DefaultRecipient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsBodyHtml {
            get {
                return ((bool)(this["IsBodyHtml"]));
            }
            set {
                this["IsBodyHtml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsNetworkCredential {
            get {
                return ((bool)(this["IsNetworkCredential"]));
            }
            set {
                this["IsNetworkCredential"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Domain")]
        public string Domain {
            get {
                return ((string)(this["Domain"]));
            }
            set {
                this["Domain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int TimeoutCallBack {
            get {
                return ((int)(this["TimeoutCallBack"]));
            }
            set {
                this["TimeoutCallBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string SMTPServer {
            get {
                return ((string)(this["SMTPServer"]));
            }
            set {
                this["SMTPServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ksayenko@gmail.com")]
        public string SMTPUser {
            get {
                return ((string)(this["SMTPUser"]));
            }
            set {
                this["SMTPUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsEnableSSl {
            get {
                return ((bool)(this["IsEnableSSl"]));
            }
            set {
                this["IsEnableSSl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\kateryna.sayenko\\Documents\\Visual Studio 2012\\Projects\\NotificationSyste" +
            "m\\NotificationSystem\\bin\\Release\\LOGS")]
        public string LogPath {
            get {
                return ((string)(this["LogPath"]));
            }
            set {
                this["LogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nizekzutmppluzaf")]
        public string SMTPPassword {
            get {
                return ((string)(this["SMTPPassword"]));
            }
            set {
                this["SMTPPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("465")]
        public int SMTPPort {
            get {
                return ((int)(this["SMTPPort"]));
            }
            set {
                this["SMTPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Write_to_System_Table {
            get {
                return ((bool)(this["Write_to_System_Table"]));
            }
            set {
                this["Write_to_System_Table"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EndarNotification")]
        public string SystemSectionName {
            get {
                return ((string)(this["SystemSectionName"]));
            }
            set {
                this["SystemSectionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LastRun")]
        public string SystemSectionInfo1 {
            get {
                return ((string)(this["SystemSectionInfo1"]));
            }
            set {
                this["SystemSectionInfo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LastEmailSend")]
        public string SystemSectionInfo2 {
            get {
                return ((string)(this["SystemSectionInfo2"]));
            }
            set {
                this["SystemSectionInfo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EnDARDatabaseNotificationService")]
        public string ServiceName {
            get {
                return ((string)(this["ServiceName"]));
            }
            set {
                this["ServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int Send_Time_Seconds {
            get {
                return ((int)(this["Send_Time_Seconds"]));
            }
            set {
                this["Send_Time_Seconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>DIVS704SQL1\MSSQLPUBLIC</string>
  <string>DIVS704SQL1\MSSQLPUBLIC</string>
  <string>DIVS704SQL1\MSSQLPUBLIC</string>
  <string>DIVS704SQL1\MSSQLPUBLIC</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Data_Source {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Data_Source"]));
            }
            set {
                this["Data_Source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ENDAR</string>
  <string>ENDAR_CIMP</string>
  <string>ENDAR_Ghent</string>
  <string>ENDAR_Ghent</string>
  <string>ENDAR_CCWQP</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection InitialCatalog {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["InitialCatalog"]));
            }
            set {
                this["InitialCatalog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>NotificationUser01</string>
  <string>NotificationUser01</string>
  <string>NotificationUser01</string>
  <string>NotificationUser01</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DatabasePassword {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DatabasePassword"]));
            }
            set {
                this["DatabasePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>NotificationUser</string>
  <string>NotificationUser</string>
  <string>NotificationUser</string>
  <string>NotificationUser</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DatabaseUser {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DatabaseUser"]));
            }
            set {
                this["DatabaseUser"] = value;
            }
        }
    }
}
